"""empty message

Revision ID: 07ecb4160481
Revises: 2ba23a5aa5ef
Create Date: 2024-09-19 00:14:19.036381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ecb4160481'
down_revision = '2ba23a5aa5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('rtype', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('geometry', sa.String(length=255), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('location')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geometry', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rtype', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('priceLevel', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('opeN', sa.Boolean(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('opeN')
        batch_op.drop_column('priceLevel')
        batch_op.drop_column('rtype')
        batch_op.drop_column('distance')
        batch_op.drop_column('geometry')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('geometry')
        batch_op.drop_column('rtype')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
