"""empty message

Revision ID: 0c1031a9a26a
Revises: 07ecb4160481
Create Date: 2024-09-29 12:55:37.200101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1031a9a26a'
down_revision = '07ecb4160481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateT', sa.DateTime(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('dateT')

    # ### end Alembic commands ###
