"""empty message

Revision ID: 899118d6a2df
Revises: 0c1031a9a26a
Create Date: 2024-09-29 13:03:30.231272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899118d6a2df'
down_revision = '0c1031a9a26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_history')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateT', sa.DateTime(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('dateT')

    op.create_table('_alembic_tmp_history',
    sa.Column('rid', sa.INTEGER(), nullable=False),
    sa.Column('rtype', sa.VARCHAR(length=100), nullable=False),
    sa.Column('geometry', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('dateT', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###
