"""empty message

Revision ID: c8615b672f6a
Revises: 95c8f2ce4784
Create Date: 2024-09-29 13:06:45.573683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8615b672f6a'
down_revision = '95c8f2ce4784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placeid', sa.String(length=100), nullable=False))
        batch_op.drop_column('rid')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placeid', sa.String(length=100), nullable=False))
        batch_op.drop_column('rid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('placeid')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rid', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('placeid')

    # ### end Alembic commands ###
